# ===============================
# APP
# ===============================
spring.application.name=sentinel

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/sentinel_db}
spring.datasource.username=${DB_USERNAME:sentinel}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# EMAIL / SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

sentinel.admin.email=${ADMIN_EMAIL}

resend.api.key=${RESEND_API_KEY}