# ===============================
# APP
# ===============================
spring.application.name=sentinel

# ===============================
# DATASOURCE (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3306/sentinel_db
spring.datasource.username=sentinel
spring.datasource.password=sentinel@123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


# ===============================
# JWT
# ===============================
jwt.secret=9k4P3mQ7xV2bL8nR5sY1dF6gH0jK9aN4pT7wE2rU8iO5cX3zM6qL1sV4yB7nH2f
jwt.expiration=86400000

server.port=${PORT:8080}